package Model;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

@Entity
public class Pergunta implements Serializable {

    @ManyToOne(targetEntity = Inquerito.class)
    private Inquerito inquerito;

    @Column(unique = true)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long IdPergunta;

    @Basic
    private String TextoPergunta;

    public Pergunta() {

    }

    public Inquerito getInquerito() {
        return this.inquerito;
    }

    public void setInquerito(Inquerito inquerito) {
        this.inquerito = inquerito;
    }

    public Long getIdPergunta() {
        return this.IdPergunta;
    }

    public void setIdPergunta(Long IdPergunta) {
        this.IdPergunta = IdPergunta;
    }

    public String getTextoPergunta() {
        return this.TextoPergunta;
    }

    public void setTextoPergunta(String TextoPergunta) {
        this.TextoPergunta = TextoPergunta;
    }
}
