package Model;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

@Entity
public class Resposta implements Serializable {

    @Basic
    private String RespCerta;

    @Column(unique = true)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long IdResposta;

    @ManyToOne(targetEntity = Pergunta.class)
    private Pergunta pergunta;

    @Basic
    private String Texto;

    public Resposta() {

    }

    public String getRespCerta() {
        return this.RespCerta;
    }

    public void setRespCerta(String RespCerta) {
        this.RespCerta = RespCerta;
    }

    public Long getIdResposta() {
        return this.IdResposta;
    }

    public void setIdResposta(Long IdResposta) {
        this.IdResposta = IdResposta;
    }

    public Pergunta getPergunta() {
        return this.pergunta;
    }

    public void setPergunta(Pergunta pergunta) {
        this.pergunta = pergunta;
    }

    public String getTexto() {
        return this.Texto;
    }

    public void setTexto(String Texto) {
        this.Texto = Texto;
    }
}
