package Model;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

@Entity
public class RespInquerito implements Serializable {

    @Column(unique = true)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long IdRespInquerito;

    @Id
    @ManyToOne(optional = false, targetEntity = Resposta.class)
    private Resposta resposta;

    @Id
    @ManyToOne(optional = false, targetEntity = UserInquerito.class)
    private UserInquerito userInquerito;

    public RespInquerito() {

    }

    public Long getIdRespInquerito() {
        return this.IdRespInquerito;
    }

    public void setIdRespInquerito(Long IdRespInquerito) {
        this.IdRespInquerito = IdRespInquerito;
    }

    public Resposta getResposta() {
        return this.resposta;
    }

    public void setResposta(Resposta resposta) {
        this.resposta = resposta;
    }

    public UserInquerito getUserInquerito() {
        return this.userInquerito;
    }

    public void setUserInquerito(UserInquerito userInquerito) {
        this.userInquerito = userInquerito;
    }
}
