package Model;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class TipoUser implements Serializable {

    @Basic
    private String Designacao;

    @Column(unique = true)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long IdTipoUser;

    public TipoUser() {

    }

    public String getDesignacao() {
        return this.Designacao;
    }

    public void setDesignacao(String Designacao) {
        this.Designacao = Designacao;
    }

    public Long getIdTipoUser() {
        return this.IdTipoUser;
    }

    public void setIdTipoUser(Long IdTipoUser) {
        this.IdTipoUser = IdTipoUser;
    }
}
