package Model;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

@Entity
public class UserInquerito implements Serializable {

    @ManyToOne(targetEntity = Inquerito.class)
    private Inquerito inquerito;

    @Column(unique = true)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long IdUserInqerito;

    @ManyToOne(targetEntity = User.class)
    private User user;

    public UserInquerito() {

    }

    public Inquerito getInquerito() {
        return this.inquerito;
    }

    public void setInquerito(Inquerito inquerito) {
        this.inquerito = inquerito;
    }

    public Long getIdUserInqerito() {
        return this.IdUserInqerito;
    }

    public void setIdUserInqerito(Long IdUserInqerito) {
        this.IdUserInqerito = IdUserInqerito;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}
